In [204]:
#This project has 2 parts, the first part involves creating several supervised machine learning models such as linear regression(regularized and non regularized), SVC, 
#lasso regression,computing the scores of the models to see which is better
#I will also use polynomial features to transform some of the data set and then fit a machine learning model to it
#The second part involves training a machine learning model to predict if a mushroom is poisonous or not




#-------------------------------------------------------PART1------------------------------------------------------#
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

#creating my own x and y datasets
np.random.seed(0)
n = 15
x = np.linspace(0,10,n) + np.random.randn(n)/5
y = np.sin(x)+x/6 + np.random.randn(n)/10

#use train_test_split to split x and y into train and test sets
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=0)

# You can use this function to help you visualize the dataset by
# plotting a scatterplot of the data points
# in the training and test sets.
def part1_scatter():
    import matplotlib.pyplot as plt
    %matplotlib notebook
    plt.figure()
    plt.scatter(X_train, y_train, label='training data')
    plt.scatter(X_test, y_test, label='test data')
    plt.legend(loc=4);
    
    


In [205]:
x1=x.reshape(-1,1)
x1.shape

In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [7]:
#the first task is to fit a polynomial LinearRegression model on the training data X_train 
#for degrees 1, 3, 6, and 9

In [60]:
#degree 1
poly1 = PolynomialFeatures(degree=1)
x1_poly1 = poly1.fit_transform(x1)
X_train, X_test, y_train, y_test = train_test_split(x1_poly1, y, random_state=0)
trip = LinearRegression().fit(X_train, y_train)

In [56]:
x1_poly1.shape

(15, 2)

In [57]:
#generate 100 numbers between 0 and 10
tests = np.linspace(0,10,100)
test1=tests.reshape(50,2)

In [58]:
test1.shape

(50, 2)

In [61]:
trip #linear regression model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [159]:
#use the linear regression model to predict the outcome/result of those 100 numbers
n1=trip.predict(test1)
n1

array([0.26920155, 0.30152425, 0.33384695, 0.36616966, 0.39849236,
       0.43081507, 0.46313777, 0.49546047, 0.52778318, 0.56010588,
       0.59242858, 0.62475129, 0.65707399, 0.6893967 , 0.7217194 ,
       0.7540421 , 0.78636481, 0.81868751, 0.85101021, 0.88333292,
       0.91565562, 0.94797832, 0.98030103, 1.01262373, 1.04494644,
       1.07726914, 1.10959184, 1.14191455, 1.17423725, 1.20655995,
       1.23888266, 1.27120536, 1.30352807, 1.33585077, 1.36817347,
       1.40049618, 1.43281888, 1.46514158, 1.49746429, 1.52978699,
       1.56210969, 1.5944324 , 1.6267551 , 1.65907781, 1.69140051,
       1.72372321, 1.75604592, 1.78836862, 1.82069132, 1.85301403])

In [69]:
#degree 3
poly3 = PolynomialFeatures(degree=3)
x1_poly3 = poly3.fit_transform(x1)
X_train, X_test, y_train, y_test = train_test_split(x1_poly3, y, random_state=0)
trips = LinearRegression().fit(X_train, y_train)

In [65]:
x1_poly3.shape

(15, 4)

In [66]:
#generate numbers and reshape the data to match x1_poly3.shape
test3 = np.linspace(0,10,100)
test3=test3.reshape(25,4)

In [70]:
trips

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [71]:
test3.shape

(25, 4)

In [160]:
#use the linear regression model to predict the outcome/result of those 100 numbers
n2=trips.predict(test3)
n2

array([ 1.18821982,  0.94624845,  0.70427709,  0.46230573,  0.22033436,
       -0.021637  , -0.26360836, -0.50557973, -0.74755109, -0.98952245,
       -1.23149382, -1.47346518, -1.71543654, -1.95740791, -2.19937927,
       -2.44135063, -2.683322  , -2.92529336, -3.16726472, -3.40923608,
       -3.65120745, -3.89317881, -4.13515017, -4.37712154, -4.6190929 ])

In [137]:
#degree 6
poly6 = PolynomialFeatures(degree=6)
x1_poly6 = poly6.fit_transform(x1)
X_train, X_test, y_train, y_test = train_test_split(x1_poly6, y, random_state=0)
tripss = LinearRegression().fit(X_train, y_train)

In [80]:
tripss

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [165]:
#generate numbers and reshape the data x1_poly6.shape
test4 = np.linspace(0,10,105)
test4 =test4.reshape(15,7)

In [166]:
test4.shape

(15, 7)

In [140]:
tripss

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [167]:
#use the linear regression model to predict the outcome/result of those 100 numbers
n3=tripss.predict(test4)
n3


array([-0.13627764,  0.77265531,  1.68158826,  2.59052121,  3.49945416,
        4.40838711,  5.31732006,  6.22625301,  7.13518596,  8.04411891,
        8.95305186,  9.86198481, 10.77091776, 11.67985071, 12.58878366])

In [143]:
X_train.shape

(11, 7)

In [149]:
poly9 = PolynomialFeatures(degree=9)
x1_poly9 = poly9.fit_transform(x1)
X_train, X_test, y_train, y_test = train_test_split(x1_poly9, y, random_state=0)
linreg = LinearRegression().fit(X_train, y_train)

In [150]:
linreg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [151]:
x1_poly9.shape

(15, 10)

In [154]:
#generate numbers and reshape the data x1_poly9.shape
test9 = np.linspace(0,10,100)
test9 =test6.reshape(10,10)

In [168]:
#use the linear regression model to predict the outcome/result of those 100 numbers
n4=linreg.predict(test9)
n4

array([ 7.05917170e+00,  3.31394770e-02, -6.99289275e+00, -1.40189250e+01,
       -2.10449572e+01, -2.80709894e+01, -3.50970216e+01, -4.21230539e+01,
       -4.91490861e+01, -5.61751183e+01])

In [174]:
import numpy as np

In [178]:
#store all the predicted values in an array
np.array([n1,n2,n3,n4])

array([array([0.26920155, 0.30152425, 0.33384695, 0.36616966, 0.39849236,
       0.43081507, 0.46313777, 0.49546047, 0.52778318, 0.56010588,
       0.59242858, 0.62475129, 0.65707399, 0.6893967 , 0.7217194 ,
       0.7540421 , 0.78636481, 0.81868751, 0.85101021, 0.88333292,
       0.91565562, 0.94797832, 0.98030103, 1.01262373, 1.04494644,
       1.07726914, 1.10959184, 1.14191455, 1.17423725, 1.20655995,
       1.23888266, 1.27120536, 1.30352807, 1.33585077, 1.36817347,
       1.40049618, 1.43281888, 1.46514158, 1.49746429, 1.52978699,
       1.56210969, 1.5944324 , 1.6267551 , 1.65907781, 1.69140051,
       1.72372321, 1.75604592, 1.78836862, 1.82069132, 1.85301403]),
       array([ 1.18821982,  0.94624845,  0.70427709,  0.46230573,  0.22033436,
       -0.021637  , -0.26360836, -0.50557973, -0.74755109, -0.98952245,
       -1.23149382, -1.47346518, -1.71543654, -1.95740791, -2.19937927,
       -2.44135063, -2.683322  , -2.92529336, -3.16726472, -3.40923608,
       -3.65120745, -3.893

In [201]:
#Write a function that fits a polynomial LinearRegression model on the training data X_train for degrees 0 through 9. 
#For each model compute the  R2 (coefficient of determination) regression score on the training data as well as the the test data, 
#and return both of these arrays in a tuple.
def answer_two():
    from sklearn.linear_model import LinearRegression
    from sklearn.preprocessing import PolynomialFeatures
    poly1 = PolynomialFeatures(degree=1)
    x1_poly1 = poly1.fit_transform(x1)
    X_train1, X_test1, y_train1, y_test1 = train_test_split(x1_poly1, y, random_state=0)
    linreg1 = LinearRegression().fit(X_train1, y_train1)
    linreg1.score(X_train1,y_train1)
    linreg1.score(X_test1,y_test1)
    
    poly2 = PolynomialFeatures(degree=2)
    x1_poly2 = poly2.fit_transform(x1)
    X_train2, X_test2, y_train2, y_test2 = train_test_split(x1_poly2, y, random_state=0)
    linreg2 = LinearRegression().fit(X_train2, y_train2)
    linreg2.score(X_train2,y_train2)
    linreg2.score(X_test2,y_test2)
    
    poly3 = PolynomialFeatures(degree=3)
    x1_poly3 = poly3.fit_transform(x1)
    X_train3, X_test3, y_train3, y_test3 = train_test_split(x1_poly3, y, random_state=0)
    linreg3 = LinearRegression().fit(X_train3, y_train3)
    linreg3.score(X_train3,y_train3)
    linreg3.score(X_test3,y_test3)
    
    poly4 = PolynomialFeatures(degree=4)
    x1_poly4 = poly4.fit_transform(x1)
    X_train4, X_test4, y_train4, y_test4 = train_test_split(x1_poly4, y, random_state=0)
    linreg4 = LinearRegression().fit(X_train4, y_train4)
    linreg4.score(X_train4,y_train4)
    linreg4.score(X_test4,y_test4)
    
    poly5 = PolynomialFeatures(degree=5)
    x1_poly5 = poly5.fit_transform(x1)
    X_train5, X_test5, y_train5, y_test5 = train_test_split(x1_poly5, y, random_state=0)
    linreg5 = LinearRegression().fit(X_train5, y_train5)
    linreg5.score(X_train5,y_train5)
    linreg5.score(X_test5,y_test5)
    
    
    poly6 = PolynomialFeatures(degree=6)
    x1_poly6 = poly6.fit_transform(x1)
    X_train6, X_test6, y_train6, y_test6 = train_test_split(x1_poly6, y, random_state=0)
    linreg6 = LinearRegression().fit(X_train6, y_train6)
    linreg6.score(X_train6,y_train6)
    linreg6.score(X_test6,y_test6)
    
    
    poly7 = PolynomialFeatures(degree=7)
    x1_poly7 = poly7.fit_transform(x1)
    X_train7, X_test7, y_train7, y_test7 = train_test_split(x1_poly7, y, random_state=0)
    linreg7 = LinearRegression().fit(X_train7, y_train7)
    linreg7.score(X_train7,y_train7)
    linreg7.score(X_test7,y_test7)
    
    
    poly9 = PolynomialFeatures(degree=9)
    x1_poly9 = poly9.fit_transform(x1)
    X_train9, X_test9, y_train9, y_test9 = train_test_split(x1_poly9, y, random_state=0)
    linreg9 = LinearRegression().fit(X_train9, y_train9)
    linreg9.score(X_train9,y_train9)
    linreg9.score(X_test9,y_test9)
    
    r2_train = np.array([linreg1.score(X_train1,y_train1),linreg2.score(X_train2,y_train2),
                         linreg3.score(X_train3,y_train3),linreg4.score(X_train4,y_train4),
                        linreg5.score(X_train5,y_train5),linreg6.score(X_train6,y_train6),
                        linreg7.score(X_test7,y_test7),linreg9.score(X_train9,y_train9)])
    r2_test = np.array([linreg1.score(X_test1,y_test1),linreg2.score(X_test2,y_test2),
                        linreg3.score(X_test3,y_test3),linreg4.score(X_test4,y_test4),
                        linreg5.score(X_test5,y_test5),linreg6.score(X_test6,y_test6),
                        linreg7.score(X_test7,y_test7),linreg9.score(X_test9,y_test9)])
    tup = (r2_train, r2_test)
    
    
    
    return tup

In [222]:
#IGNORE THIS PART
from sklearn.metrics.regression import r2_score
poly1 = PolynomialFeatures(degree=1)
x1_poly1 = poly1.fit_transform(x1)
X_train1, X_test1, y_train1, y_test1 = train_test_split(x1_poly1, y, random_state=0)
linreg1 = LinearRegression().fit(X_train1, y_train1)
t=linreg1.score(X_train1,y_train1)
i=linreg1.score(X_test1,y_test1)

In [217]:
#IGNORE THIS PART
r2_score= linreg1.score(X_train1,y_train1)
r2_score

0.4292457781234663

In [226]:
#IGNORE THIS PART
p=linreg1.predict(X_test1)
i=linreg1.score(X_test1,y_test1)
p
i

-0.45237104233936676

In [195]:
#IGNORE THIS PART
tu = (t,i)

In [196]:
#IGNORE THIS PART
tu

(0.4292457781234663, -0.45237104233936676)

In [202]:
answer_two()

(array([0.42924578, 0.4510998 , 0.58719954, 0.91941945, 0.97578641,
        0.99018233, 0.92021504, 0.99803706]),
 array([-0.45237104, -0.06856984,  0.00533105,  0.73004943,  0.87708301,
         0.9214094 ,  0.92021504, -0.64524777]))

In [ ]:
#ans = #use series..

In [230]:
#For this question, train two models: a non-regularized LinearRegression model (default parameters) 
#and a regularized Lasso Regression model (with parameters alpha=0.01, max_iter=10000) both on polynomial features of degree 12. 
#Return the  R2  score for both the LinearRegression and Lasso model's test sets.
def answer_four():
    from sklearn.preprocessing import PolynomialFeatures
    from sklearn.linear_model import Lasso, LinearRegression
    from sklearn.metrics.regression import r2_score
    poly12 = PolynomialFeatures(degree=12)
    x1_poly12 = poly1.fit_transform(x1)
    X_train, X_test, y_train, y_test = train_test_split(x1_poly12, y,random_state = 0)
    check = LinearRegression().fit(X_train, y_train)
    linlass = Lasso(alpha=0.01, max_iter = 10000).fit(X_train, y_train)
    r2_scorelin = check.score(X_test, y_test)
    r2_scorelass = linlass.score(X_test,y_test)
    scores = (r2_scorelin,r2_scorelass)
    return scores

In [397]:
#IGNORE THIS PART
trains = linlass.predict(X_test)
trains

array([0.38452701, 0.97004112, 1.16374477, 1.29369313])

In [398]:
#IGNORE THIS PART
r2_score(y_test,trains)

-0.4503948042064918

In [399]:
answer_four()

(-0.45237104233936676, -0.4503948042064918)

In [ ]:
#----------------------------------------------------PART2-----------------------------------------------------------#

In [ ]:
#For this section we will be working with the UCI Mushroom Data Set stored in mushrooms.csv. 
#The data will be used to train a model to predict whether or not a mushroom is poisonous. 
#

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


mush_df = pd.read_csv('mushrooms.csv')
mush_df2 = pd.get_dummies(mush_df) #converts categorical data to numeric or indicators

X_mush = mush_df2.iloc[:,2:]
y_mush = mush_df2.iloc[:,1]


X_train22, X_test22, y_train22, y_test22 = train_test_split(X_mush, y_mush, random_state=0)

# For performance reasons in Questions 6 and 7, we will create a smaller version of the
# entire mushroom dataset for use in those questions.  For simplicity we'll just re-use
# the 25% test split created above as the representative subset.
#
# Use the variables X_subset, y_subset for Questions 6 and 7.
X_subset = X_test22
y_subset = y_test22

In [3]:
mush_df2.head()

class_e  class_p  cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  \
0        0        1            0            0            0            0   
1        1        0            0            0            0            0   
2        1        0            1            0            0            0   
3        0        1            0            0            0            0   
4        1        0            0            0            0            0   

   cap-shape_s  cap-shape_x  cap-surface_f  cap-surface_g    ...      \
0            0            1              0              0    ...       
1            0            1              0              0    ...       
2            0            0              0              0    ...       
3            0            1              0              0    ...       
4            0            1              0              0    ...       

   population_s  population_v  population_y  habitat_d  habitat_g  habitat_l  \
0             1             0             0          0          0          0   
1             0             0             0          0          1          0   
2             0             0             0          0          0          0   
3             1             0             0          0          0          0   
4             0             0             0          0          1          0   

   habitat_m  habitat_p  habitat_u  habitat_w  
0          0          0          1          0  
1          0          0          0          0  
2          1          0          0          0  
3          0          0          1          0  
4          0          0          0          0  

[5 rows x 119 columns]

In [246]:
X_mush.head()

cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            1            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  cap-surface_y  \
0            1              0              0              1              0   
1            1              0              0              1              0   
2            0              0              0              1              0   
3            1              0              0              0              1   
4            1              0              0              1              0   

     ...      population_s  population_v  population_y  habitat_d  habitat_g  \
0    ...                 1             0             0          0          0   
1    ...                 0             0             0          0          1   
2    ...                 0             0             0          0          0   
3    ...                 1             0             0          0          0   
4    ...                 0             0             0          0          1   

   habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0          0          0          0          1          0  
1          0          0          0          0          0  
2          0          1          0          0          0  
3          0          0          0          1          0  
4          0          0          0          0          0  

[5 rows x 117 columns]

In [247]:
y_mush.head()

0    1
1    0
2    0
3    1
4    0
Name: class_p, dtype: uint8

In [4]:
X_train22.columns

Index(['cap-shape_b', 'cap-shape_c', 'cap-shape_f', 'cap-shape_k',
       'cap-shape_s', 'cap-shape_x', 'cap-surface_f', 'cap-surface_g',
       'cap-surface_s', 'cap-surface_y',
       ...
       'population_s', 'population_v', 'population_y', 'habitat_d',
       'habitat_g', 'habitat_l', 'habitat_m', 'habitat_p', 'habitat_u',
       'habitat_w'],
      dtype='object', length=117)

In [16]:
#Using X_train2 and y_train2,train a DecisionTreeClassifier with default parameters and random_state=0. 
#for this section I want to determine the 5 most important features found by the decision tree
def answer_five():
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.model_selection import train_test_split
    X_train22, X_test22, y_train22, y_test22 = train_test_split(X_mush, y_mush, random_state=0)
    clf = DecisionTreeClassifier().fit(X_train22, y_train22)
    p=sorted(clf.feature_importances_)
    
    for i in range(117):
        it =(clf.feature_importances_[i],X_train22.columns[i])
        
        if clf.feature_importances_[i] >0:
            new = X_train22.columns[i]
            print(new)
        
    
    
        
      


In [17]:
answer_five()

cap-shape_c
cap-surface_g
bruises_t
odor_a
odor_l
odor_n
gill-size_b
stalk-root_c
stalk-root_r
stalk-surface-below-ring_y
ring-number_t
ring-type_p
spore-print-color_r


In [ ]:
#Validation curve does 3 fold k cross validation by default. 
#Helps us see the sensitivity to changes in an important parameter or 
#what parameter is best to use
#the function takes in the name of the classifer, the x and y data sets, 
#the name of parameter to sweep and an array of values to use for the parameter
#the function returns an array - each row corresponds to a value that was swept over
#and the number of columns is the number of cross validation folds

In [411]:
#For this section, we're going to use the validation_curve function in sklearn.model_selection to determine training and test scores for a Support Vector Classifier (SVC) 
#with varying parameter values.
#I found the mean score across the three models for each level of gamma for both arrays,creating two arrays of length 6, and return a tuple with the two arrays.
def answer_six():
    from sklearn.svm import SVC
    from sklearn.model_selection import validation_curve
    clf1 = SVC(kernel = 'rbf',C = 1)
    param_range = np.logspace(-4, 1, 6)
    train_scores, test_scores = validation_curve(clf1, X_subset, y_subset,param_name='gamma',
                                            param_range=param_range, cv=3)
    final = (train_scores.mean(axis=1),test_scores.mean(axis=1))

    

    return final

In [413]:
answer_six()

(array([0.56647847, 0.93155951, 0.99039881, 1.        , 1.        ,
        1.        ]),
 array([0.56768547, 0.92959558, 0.98965952, 1.        , 0.99507994,
        0.52240279]))